/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPainelRouteImport } from './routes/admin.painel'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/admin/painel',
  path: '/admin/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/fila': typeof FilaRoute
  '/portal': typeof PortalRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/fila': typeof FilaRoute
  '/portal': typeof PortalRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/fila': typeof FilaRoute
  '/portal': typeof PortalRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entrar' | '/fila' | '/portal' | '/admin/painel' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entrar' | '/fila' | '/portal' | '/admin/painel' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/fila'
    | '/portal'
    | '/admin/painel'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  FilaRoute: typeof FilaRoute
  PortalRoute: typeof PortalRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/painel': {
      id: '/admin/painel'
      path: '/admin/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  FilaRoute: FilaRoute,
  PortalRoute: PortalRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
